trigger:
  - main   # branch ka naam

pool:
  vmImage: 'windows-latest'

steps:

# Step 1: Create dummy folder and file
- script: |
    mkdir $(Build.ArtifactStagingDirectory)/OnlineBookArtifact
    echo "This is a placeholder artifact for Online Book Project" > $(Build.ArtifactStagingDirectory)/OnlineBookArtifact/readme.txt
  displayName: 'Create Dummy Artifact'

# Step 2: Publish dummy artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/OnlineBookArtifact'
    ArtifactName: 'OnlineBookArtifact'
    publishLocation: 'Container'
